let emoji = [
    ":eyes:",
    ":watermelon:",
    ":cowboy:",
    ":innocent:",
    ":partying_face:",
    ":heart_eyes:",
    ":brain:",
    ":alien:",
    ":space_invader:"
    ":cat:",
    :mouse:
    :hamster:
    :rabbit:
    :bear:
    :teddy_bear:
    :panda_face:
    :koala:
    :tiger:
    :lion_face:
    :cow:
    :pig:
    :pig_nose:
    :frog:
    :monkey_face:
    :see_no_evil:
    :hear_no_evil:
    :speak_no_evil:
    :monkey:
    :gorilla:
    :orangutan:
    :chicken:
    :penguin:
    :bird:
    :baby_chick:
    :hatching_chick:
    :hatched_chick:
    :wolf:
    :fox:
    :raccoon:
    :boar:
    :horse:
    :zebra:
    :giraffe:
    :deer:
    :kangaroo:
    :sloth:
    :otter:
    :unicorn:
    :bee:
    :bug:
    :butterfly:
    :snail:
    :beetle:
    :ant:
    :cricket:
    :spider:
    :spider_web:
    :scorpion:
    :mosquito:
    :microbe:
    :turtle:
    :snake:
    :lizard:
    :octopus:
    :squid:
    :lobster:
    :crab:
    :shrimp:
    :oyster:
    :tropical_fish:
    :fish:
    :blowfish:
    :dolphin:
    :shark:
    :whale:
    :whale2:
    :crocodile:
    :leopard:
    :tiger2:
    :water_buffalo:
    :ox:
    :cow2:
    :dromedary_camel:
    :camel:
    :llama:
    :elephant:
    :rhino:
    :hippopotamus:
    :goat:
    :ram:
    :sheep:
    :racehorse:
    :pig2:
    :bat:
    :rooster:
    :turkey:
    :dove:
    :eagle:
    :duck:
    :swan:
    :owl:
    :flamingo:
    :peacock:
    :parrot:
    :dog2:
    :guide_dog:
    :service_dog:
    :poodle:
    :cat2:
    :rabbit2:
    :rat:
    :mouse2:
    :chipmunk:
    :skunk:
    :badger:
    :hedgehog:
    :feet:
    :dragon:
    :dragon_face:
    :sauropod:
    :t_rex:
    :cactus:
    :christmas_tree:
    :evergreen_tree:
    :deciduous_tree:
    :palm_tree:
    :seedling:
    :herb:
    :shamrock:
    :four_leaf_clover:
    :bamboo:
    :tanabata_tree:
    :leaves:
    :fallen_leaf:
    :maple_leaf:
    :ear_of_rice:
    :hibiscus:
    :sunflower: 
    :rose: :wilted_rose: :tulip: :blossom: :cherry_blossom: :bouquet: :mushroom: :chestnut: :shell: :earth_americas: :earth_africa: :earth_asia: :full_moon: :waning_gibbous_moon: :last_quarter_moon: :waning_crescent_moon: :new_moon: :waxing_crescent_moon: :first_quarter_moon: :waxing_gibbous_moon: :crescent_moon: :new_moon_with_face: :full_moon_with_face: :first_quarter_moon_with_face: :last_quarter_moon_with_face: :star: :star2: :dizzy: :sparkles: :comet: :ringed_planet: :sun_with_face: :sunny: :white_sun_small_cloud: :partly_sunny: :white_sun_cloud: :white_sun_rain_cloud: :cloud: :cloud_rain: :thunder_cloud_rain: :cloud_lightning: :zap: :fire: :boom: :snowflake: :cloud_snow: :snowman2: :snowman: :wind_blowing_face: :dash: :cloud_tornado: :fog: :rainbow: :umbrella: :droplet: :sweat_drops: :ocean::dog: :cat: :mouse: :hamster: :rabbit: :bear: :teddy_bear: :panda_face: :koala: :tiger: :lion_face:
    ];

function emoji() {

}